Controllers/CartController.cs
using ecomerce1.Models;
using ecomerce1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ecomerce1.Controllers
{
    public class CartController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<applicationUser> userManager;
        private readonly decimal shippingFee;

        public CartController(ApplicationDbContext context, IConfiguration configuration ,
            UserManager<applicationUser> userManager)
        {
            this.context = context;
            this.userManager = userManager;
            shippingFee = configuration.GetValue<decimal>("CartSettings:shippingFee");
        }
        public IActionResult Index()
        {
            List<OrderItem> cartItems = CartHelper.GetCartItems(Request, Response, context);
            decimal subtotal = CartHelper.GetSubtotal(cartItems);

            ViewBag.CartItems = cartItems;
            ViewBag.shippingFee = shippingFee;
            ViewBag.Subtotal = subtotal;
            ViewBag.Total = subtotal + shippingFee; 

            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Index(CheckoutDto model)
        {
            List<OrderItem> cartItems = CartHelper.GetCartItems(Request, Response, context);
            decimal subtotal = CartHelper.GetSubtotal(cartItems);

            ViewBag.CartItems = cartItems;
            ViewBag.shippingFee = shippingFee;
            ViewBag.Subtotal = subtotal;
            ViewBag.Total = subtotal + shippingFee;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // check if shopping cart is empty or not 
            if (cartItems.Count == 0)
            {
                ViewBag.ErrorMessage = "Your cart is empty";
                return View(model);
            }

            TempData["DeliveryAddress"] = model.DeliveryAddress;
            TempData["PaymentMethod"] = model.PaymentMethod;


            if (model.PaymentMethod == "paypal" || model.PaymentMethod == "Credit_card") 
            {
                return RedirectToAction("Index", "checkout");
            }

            return RedirectToAction("Confirm");

        }


        public IActionResult Confirm() 
        {
            List<OrderItem> cartItems = CartHelper.GetCartItems(Request, Response, context);
            decimal total = CartHelper.GetSubtotal(cartItems) + shippingFee ;

            int cartSize = 0;
            foreach(var item in cartItems)
            {
                cartSize += item.Quantity; 
            }
            
            string deliveryAddress = TempData["DeliveryAddress"] as string ?? "";
            string paymentMethod = TempData["PaymentMethod"] as string ?? "";

            //Console.WriteLine("        deliveryAddress:" + deliveryAddress + "       paymentMethod:" + paymentMethod);

            TempData.Keep();

           // Console.WriteLine("cartSize:" + cartSize + "        deliveryAddress:" + deliveryAddress + "       paymentMethod:" + paymentMethod); 

            if (cartSize == 0 || deliveryAddress.Length == 0 || paymentMethod.Length == 0) 
            {
                return RedirectToAction("Index","Home");
            }

            ViewBag.DeliveryAddress = deliveryAddress;    
            ViewBag.PaymentMethod = paymentMethod;    
            ViewBag.Total = total ;
            ViewBag.CartSize = cartSize ;
            
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Confirm(int any)
        {
            var cartItems = CartHelper.GetCartItems(Request, Response, context);
            
            string deliveryAddress = TempData["DeliveryAddress"] as string ?? "";
            string paymentMethod = TempData["PaymentMethod"] as string ?? "";
            TempData.Keep();

            if (cartItems.Count == 0 || deliveryAddress.Length == 0 || paymentMethod.Length == 0)
            {
                return RedirectToAction("Index", "Home");
            }


            var appUser = await userManager.GetUserAsync(User);
            if (appUser == null)
            {
                return RedirectToAction("Index", "Home");
            }


            // Save the Order 
            var order = new Order
            {
                ClientId = appUser.Id,
                Items = cartItems,
                ShippingFee = shippingFee, 
                DeliveryAddress = deliveryAddress,
                PaymentMethod = paymentMethod,
                PaymentStatus = "Pending" , 
                PaymentDetails = "",
                OrderStatus  = "created" ,
                CreatedAt = DateTime.Now,
            };
           
            context.Orders.Add(order);
            context.SaveChanges();

            // delete the shopping cart cookie 

            Response.Cookies.Delete("shopping_cart");

            ViewBag.SuccessMessage = "Order created successfully";

            return View();


        }

    }
}

Controllers/accountController.cs
using ecomerce1.Models;
using ecomerce1.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
//this is my comment !!!
// this is another comment with Hamzahhhhhh
//this is hamzazh comment
namespace ecomerce1.Controllers
{
    public class accountController : Controller
    {
        private readonly UserManager<applicationUser> userManager;
        private readonly SignInManager<applicationUser> signInManager;
        private readonly IConfiguration configuration;

        public accountController(UserManager<applicationUser> userManager,
            SignInManager<applicationUser> signInManager, IConfiguration configuration)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.configuration = configuration;
        }
        public IActionResult Register()
        {
            if (signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(registerDto registerDto)
        {
            if (signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                return View(registerDto);
            }
            //Create a new account and authenticate the user
            var user = new applicationUser()
            {
                firstName = registerDto.firstName,
                secondName = registerDto.secondName,
                UserName = registerDto.email,
                Email = registerDto.email,
                PhoneNumber = registerDto.phoneNumber,
                address = registerDto.address,
                createdAt = DateTime.Now
            };

            var result = await userManager.CreateAsync(user, registerDto.password);

            if (result.Succeeded)
            {
                //successful user registration
                await userManager.AddToRoleAsync(user, "client");

                //sign in the new user
                await signInManager.SignInAsync(user, false);

                return RedirectToAction("Index", "Home");

            }

            //register failed => show registeration errors
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View(registerDto);
        }

        public async Task<IActionResult> Logout()
        {
            if (signInManager.IsSignedIn(User))
            {
                await signInManager.SignOutAsync();
            }
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Login()
        {
            if (signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginDto loginDto)
        {
            if (signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                return View(loginDto);
            }

            var reslut = await signInManager.PasswordSignInAsync(loginDto.Email, loginDto.Password
                , loginDto.RememberMe, false);

            if (reslut.Succeeded )
            { 
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ErroMessage = "Invalid login attempt";
            }



            return View();
        }

        [Authorize]
        public async Task<IActionResult> Profile()
        {
            var appUser = await userManager.GetUserAsync(User);
            if (appUser == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var profileDto = new ProfileDto()
            {
                firstName = appUser.firstName,
                secondName = appUser.secondName,
                email = appUser.Email ?? "",
                phoneNumber = appUser.PhoneNumber,
                address = appUser.address,

            };
            return View(profileDto);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Profile(ProfileDto profileDto)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ErrorMessage = "Please fill all the required fields with valid values";
                return View(profileDto);
            }

            //Get the current user 
            var appUser = await userManager.GetUserAsync(User);
            if (appUser == null)
            {
                return RedirectToAction("Index", "Home");
            }


            //Update the user profile 
            appUser.firstName = profileDto.firstName;
            appUser.secondName = profileDto.secondName;
            appUser.UserName = profileDto.email;
            appUser.Email = profileDto.email;
            appUser.PhoneNumber = profileDto.phoneNumber;
            appUser.address = profileDto.address;

            var result = await userManager.UpdateAsync(appUser);
            if (result.Succeeded)
            {
                ViewBag.SuccessMessage = "Profile updated successfully";
            }
            else
            {
                ViewBag.ErrorMessage = "unable to update the profile: " + result.Errors.First().Description;
            }


            return View(profileDto);
        }

        [Authorize]
        public IActionResult Password()
        {
            return View();
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Password(PasswordDto passwordDto)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            //Get the current user 
            var appUser = await userManager.GetUserAsync(User);
            if (appUser == null)
            {
                return RedirectToAction("Index", "Home");
            }

            //update the password 
            var result = await userManager.ChangePasswordAsync(appUser,
                passwordDto.Currentpassword, passwordDto.Newpassword);

            if (result.Succeeded)
            {
                ViewBag.SuccessMessage = "Password updated Successfully";
            }
            else
            {
                ViewBag.ErrorMessage = "Error: " + result.Errors.First().Description;
            }

            return View(passwordDto);
        }




        public IActionResult AccessDenied()
        {
            return RedirectToAction("Index", "Home");
        }

        public IActionResult ForgotPassword()
        {
            if (signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ForgotPassword([Required, EmailAddress] string email)
        {
            if (signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.Email = email;
            if (!ModelState.IsValid)
            {
                ViewBag.EmailError = ModelState["email"]?.Errors.First().ErrorMessage ?? "Invalid Email address!";
                return View();
            }
            var user = await userManager.FindByEmailAsync(email);
           
            if (user != null)
            {
                //Generate password rest token
                var token = await userManager.GeneratePasswordResetTokenAsync(user);
                string resetUrl = Url.ActionLink("ResetPassword", "Account", new { token }) ?? "URL Error";
                //Console.WriteLine("password rest token: " + resetUrl);
                //send Url by Email
                string senderName = configuration["BrevoSettings:SenderName"] ?? "";
                string senderEmail = configuration["BrevoSettings:SenderEmail"] ?? "";
                string username = user.firstName + " " + user.secondName;
                string subject = "Password Reset";
                string message = "Dear " + username + ", \n \n" +
                                 "You can Reset Your password using the following link: \n \n" +
                                 resetUrl + "\n \n" + "Best Regards";


                EmailSender.SendEmail(senderName, senderEmail, username, email, message, subject);

                ViewBag.SuccessMessage = "please check your email and click on the passwird Rest Link";
            }
            else
            {
                ViewBag.EmailError = "please enter a registerd email";
            }


            return View();

        }

        public IActionResult ResetPassword(string? token)
        {
            if (signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index", "Home");
            }
            if (token == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ResetPassword(string? token, PasswordResetDto model)
        {
            if (signInManager.IsSignedIn(User))
            {
                return RedirectToAction("Index", "Home");
            }
            if (token == null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (!ModelState.IsValid) 
            {
                return View(model);
            }
            var user = await userManager.FindByEmailAsync(model.Email);

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CodeBerry</title>
    <link rel="icon" href="/images/codeberry_solutions_logo.jpg" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ecomerce1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>

    <script>
    
        function getShoppingCart() {
            //document.cookie contains all the cookies of our website with the following format ;
            //cookie1 = value1 ; cookie2 = value2 ; coookie3 = value3 ;
            const cookieName = "shopping_cart";
            let cookiesArray = document.cookie.split(';');
            for(let i = 0 ; i<cookiesArray.length ; i++ ) {
                let cookie = cookiesArray[i] ;
                if (cookie.includes(cookieName)) {
                    let cookie_value = cookie.substring(cookie.indexOf('=') + 1) ; 
                    
                    try {
                        let cart = JSON.parse(atob(cookie_value));
                        return cart ;
                    } 
                    catch(exception) {
                        break ; 
                    }
                }
            }
            return {} ; 
        }

        function saveCart(cart) {
            let cartStr = btoa(JSON.stringify(cart))
                //save cookie 
                let d =new Date(); 
                d.setDate(d.getDate() + 365  ) ; // this cookies expiers after 365 days (one year)
                let expires = d.toUTCString();
                document.cookie = "shopping_cart=" + cartStr + ";expires=" +  expires + ";path=/; SameSite = Strict; Secure"   
        }


        function addToCart(button,id) {
            let cart = getShoppingCart() ; 
            let quantity  =  cart[id] ; 
            if (isNaN(quantity)) {
                //quantity is not a number  => set quantity to  1  
                cart[id] = 1 

               
            } 

            else {
                cart[id] = Number(quantity) + 1 ; 
            }
            saveCart(cart) ; 
            button.innerHTML = "Added <i class='bi bi-check-lg' > </i>" ; 

            let cartSize = 0 ; 
            for(var cartItem of Object.entries(cart) ) {
                quantity = cartItem[1]
                if (isNaN (quantity) )  continue ; 
                cartSize += Number(quantity) 
                
                
            }

            document.getElementById("CartSize").innerHTML = cartSize 
        }


        function increase(id)
        {
            let cart = getShoppingCart();
            let quantity = cart[id] ; 

            if (isNaN(quantity)) {
                cart[id] = 1 
            } 
            else {
                cart[id] = Number(quantity) + 1 
            }

            saveCart(cart) 
            location.reload()
        }

         function decrease(id)
         {
            let cart = getShoppingCart();

            let quantity = cart[id] ;

            if (isNaN(quantity)) {
                return
            }

            quantity = Number(quantity)

            if (quantity > 1 ) 
            {
                cart[id] = quantity - 1
                saveCart(cart)
                location.reload()
            }

              if (quantity == 1 )
            {
                delete cart[id]
                saveCart(cart)
                location.reload()
            }

            

            
        }


        function remove(id) 
        {
            let cart =  getShoppingCart() ; 

            if (cart[id])
            {
                delete cart[id]
                saveCart(cart)
                location.reload()
            }
        }

    </script>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/codeberry_solutions_logo.jpg" alt="...."  width="30" class="me-2" style="padding-bottom: 4px" />
                    CodeBerry
                    </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>+
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="store" asp-action="Index">Store</a>
                        </li>
      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>

                    <ul class="navbar-nav me-2">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                <i class="bi bi-bag-check-fill" style="font-size:25.5px"></i>
                                <span id="CartSize" class="badge rounded-pill bg-danger" style="vertical-align:top  ; font-size:10px">
                                    @CartHelper.GetCartSize(Context.Request, Context.Response)
                                </span>
                            </a>

                        </li>

                      
                    </ul>

                    @using Microsoft.AspNetCore.Identity
                    @using ecomerce1.Services
                    @inject SignInManager<applicationUser> SignInManager
                    @inject UserManager<applicationUser> UserManager

                    @if (SignInManager.IsSignedIn(User))

                    {
                        var appUser = await UserManager.GetUserAsync(User);

                        Console.WriteLine("************" + User.IsInRole("Admin") + "****************");

                        if (User.IsInRole("Admin"))
                        {
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        @(appUser!.firstName + " " + appUser!.secondName + " (Admin)")
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Index">Products</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="AdminOrders" asp-action="Index">Orders</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="account" asp-action="Profile">Profile</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="account" asp-action="Logout">Logout</a></li>
                                    </ul>
                                </li>
                            </ul>
                        }
                        else if (User.IsInRole("client"))
                        {
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        @(appUser!.firstName + " " + appUser!.secondName + " (client)")
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" asp-area="" asp-controller="ClientOrders" asp-action="Index">Orders</a></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="account" asp-action="Profile">Profile</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" asp-area="" asp-controller="account" asp-action="Logout">Logout</a></li>
                                    </ul>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <ul class="navbar-nav">



                                <li><a class="nav-link text-dark" asp-area="" asp-controller="account" asp-action="Logout">Logout</a></li>


                            </ul>
                        }
                        

                    }
                   else 
                     { 
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="btn btn-outline-primary me-2" asp-area="" asp-controller="account" asp-action="Register">Register</a>
                            </li>

                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="" asp-controller="account" asp-action="Login">Login</a>
                            </li>
                        </ul>
                    }




                </div>
            </div>
        </nav>
    </header>
    @if(ViewData["HomePage"] == null)
    {
        <div class="container mt-3">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        
    } else
    {
        @RenderBody()
    }
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <img src="/images/codeberry_solutions_logo.jpg" alt="...." width="30" class="me-2" />
            &copy; 2025 - CodeBerry - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>